server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: KHOA-SERVICE
          uri: lb://KHOA-SERVICE
          predicates:
            - Path=/khoa/**
        - id: SINHVIEN-SERVICE
          uri: lb://SINHVIEN-SERVICE
          predicates:
            - Path=/sinhvien/**
  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://localhost:8888
